### ISSUE TITLE
LDAvis display chinese problem

### ISSUE THREAD

**Issue by niutyut** [cpsievert/LDAvis#49] opened 2015-11-28 08:27 UTC
i am chinese user of LDAvis ,when i display chinese language ,i find its messy code,
lda.vis <- topicmodels_json_ldavis(title.abstract.model, myCorp, tfidf_dtm)
##visualize lda model
serVis(lda.vis)

how to do it  with UTF-8 or gbk?
please help me!!thank you

**Comment by cpsievert** [comment] 2015-12-03 06:34
Duplicate of #44

**Closed by cpsievert** 2015-12-03 06:34 UTC
