### ISSUE TITLE
Plot dimensions of LDAvis for shiny/shinydashboard

### ISSUE THREAD

**Issue by marcelopita** [cpsievert/LDAvis#64] opened 2016-08-23 16:40 UTC
Hi,
Is there an effective way of adjusting plot dimensions (e.g. width, height) of LDAvis?
I am using it in shinydashboard (renderVis and visOutput functions), but plots exceed dashboard body dimensions. Using box doesn't make difference...
Thank you.
Marcelo Pita

**Comment by MarcinKosinski** [comment] 2016-09-29 10:29
Maybe this will help you?
https://github.com/cpsievert/LDAvis/issues/66#issuecomment-250429248

**Comment by marcelopita** [comment] 2016-09-29 12:04
Yes, thank you. After a while I was naturally induced to modify Javascript code, although I was initially thinking it could be defined in the high level LDAvis API. But it's OK, solved the problem. Thank you again.

**Comment by cpsievert** [comment] 2018-04-24 20:03
Duplicate of #66

**Closed by cpsievert** 2018-04-24 20:03 UTC

**Comment by NoelMartinez-cx** [comment] 2019-10-30 17:50
> Yes, thank you. After a while I was naturally induced to modify Javascript code, although I was initially thinking it could be defined in the high level LDAvis API. But it's OK, solved the problem. Thank you again.

Hi guys! Did you find how to resolve this issue? Could you share an example? Thank so much!

**Comment by Melona17** [comment] 2020-01-21 21:00
> Yes, thank you. After a while I was naturally induced to modify Javascript code, although I was initially thinking it could be defined in the high level LDAvis API. But it's OK, solved the problem. Thank you again.

Could you please share the code to know how it's possible?
