### ISSUE TITLE
dist() with jensenShannon returns Nan 

### ISSUE THREAD

**Issue by lmkirvan** [cpsievert/LDAvis#55] opened 2016-04-22 17:31 UTC
I can't quit figure out why (as the jensen Shannon distance function looks okay) but 

`jensenShannon <- function(x, y) {
  m <- 0.5*(x + y)
  0.5*sum(x*log(x/m)) + 0.5*sum(y*log(y/m))
}

dist.mat <- proxy::dist(x = phi, method = jensenShannon)`

returns Nan using phi.

**Comment by cpsievert** [comment] 2016-06-27 23:53
duplicate of #56

**Closed by cpsievert** 2016-06-27 23:53 UTC
